// Quotes.swift
import Foundation

let quotes = [
    "Hạnh phúc không phải là đích đến, mà là hành trình chúng ta đang đi.",
    "Thành công lớn nhất là đứng dậy sau mỗi lần vấp ngã.",
    "Người hạnh phúc không phải có nhiều nhất, mà là biết đủ nhất.",
    "Đừng đếm những gì bạn mất, hãy trân trọng những gì bạn còn.",
    "Một nụ cười có thể thay đổi cả ngày của bạn.",
    "Kiên nhẫn là chìa khóa của mọi cánh cửa thành công.",
    "Hãy sống như thể bạn sẽ chết vào ngày mai, học như thể bạn sẽ sống mãi mãi.",
    "Thời gian là tài sản quý giá nhất của con người.",
    "Cơ hội thường đến ngụy trang dưới dạng thử thách.",
    "Người thông minh học từ mọi người, kẻ ngốc nghĩ mình biết tất cả.",
    "Không có con đường nào dẫn đến hạnh phúc, hạnh phúc chính là con đường.",
    "Sống là cho đi, không chỉ nhận lại.",
    "Khi bạn thay đổi cách nhìn, thế giới quanh bạn cũng thay đổi.",
    "Dám nghĩ dám làm là khởi đầu của mọi thành công.",
    "Đừng sợ thất bại, hãy sợ việc không bao giờ cố gắng.",
    "Thất bại chỉ là một cơ hội để bắt đầu lại thông minh hơn.",
    "Tri thức là sức mạnh.",
    "Làm việc chăm chỉ đánh bại tài năng khi tài năng không chăm chỉ.",
    "Đừng chờ đợi, thời gian sẽ không bao giờ hoàn hảo.",
    "Hãy là chính bạn, tất cả những người khác đã có sẵn rồi.",
    "Giá trị của con người không nằm ở những gì anh ta có, mà ở những gì anh ta cho đi.",
    "Thành công là tập hợp của những nỗ lực nhỏ được lặp lại mỗi ngày.",
    "Người lạc quan nhìn thấy cơ hội trong khó khăn.",
    "Nếu bạn muốn đi nhanh, hãy đi một mình. Nếu bạn muốn đi xa, hãy đi cùng nhau.",
    "Hãy làm việc chăm chỉ trong im lặng và để thành công lên tiếng.",
    "Sự thay đổi bắt đầu từ chính bạn.",
    "Không có gì quý hơn độc lập tự do.",
    "Người hạnh phúc biến mọi điều bình thường thành phi thường.",
    "Khát vọng là nhiên liệu của thành công.",
    "Hãy luôn biết ơn vì những gì bạn đang có.",
    "Đường xa vạn dặm bắt đầu từ một bước chân.",
    "Đừng nhìn đồng hồ, hãy làm như nó đang làm – tiếp tục tiến về phía trước.",
    "Tương lai thuộc về những ai tin vào vẻ đẹp của giấc mơ.",
    "Hãy là lý do khiến ai đó mỉm cười hôm nay.",
    "Khi một cánh cửa đóng lại, một cánh cửa khác sẽ mở ra.",
    "Học không bao giờ là đủ.",
    "Người mạnh mẽ không bao giờ ngừng mơ ước.",
    "Hãy sống trọn vẹn từng khoảnh khắc.",
    "Sự giản đơn là đỉnh cao của tinh tế.",
    "Thành công không đến với bạn, bạn phải đi đến với nó.",
    "Điều vĩ đại nhất bạn có thể học là học cách yêu thương và được yêu thương.",
    "Cuộc sống là 10% những gì xảy đến với bạn và 90% cách bạn phản ứng lại.",
    "Người khôn ngoan tạo ra nhiều cơ hội hơn là tìm thấy.",
    "Chia sẻ niềm vui sẽ nhân đôi hạnh phúc.",
    "Bạn chính là điều bạn tin tưởng.",
    "Không gì là không thể với một trái tim quyết tâm.",
    "Đừng bao giờ từ bỏ ước mơ chỉ vì mất thời gian – thời gian sẽ trôi qua dù bạn làm hay không.",
    "Hãy lắng nghe nhiều hơn nói.",
    "Cách tốt nhất để dự đoán tương lai là tạo ra nó.",
    "Hãy trở thành sự thay đổi mà bạn muốn thấy trên thế giới."
]

